docs/openapi.yml

📚 canvas では

---

docs/openapi.yml
interfaces/handler/types_gen.go

commit を見てくれ
uuid の書式も統一したさがある
(全部 `xxxxxxxx-xxxx-xxxx-Nxxx-xxxxxxxxxxxx` か全部単一の UUID)

Validate openapi

---

docs/openapi.yml
interfaces/handler/types_gen.go

Room->RoomDetail
NewRoom->Room
NewRoomRequest->CreateRoomRequest
name->username

:art: Rename openapi parameters

---

infrastructure/wire.go
infrastructure/wire_gen.go
interfaces/handler/handler.go
interfaces/handler/refill.go
interfaces/handler/room.go
interfaces/handler/types_gen.go
interfaces/handler/ws.go
interfaces/repository/errors.go
interfaces/repository/repository_impl.go
interfaces/repository/room_impl.go
model/room.go
model/user.go
usecases/repository/repository.go
usecases/repository/room.go
usecases/service/service.go
util/random/random.go

:sparkles: Add CreateRoom

---

docs/openapi.yml
oapi/gen.go
oapi/types.go

canvasとtimeLimitの追加

---

docs/openapi.yml
oapi/types.go

- :books: Add roomId pattern
- :books: fix
- :books: Add description
- :books: Use allof

Openapiのドキュメント整理

---

docs/openapi.yml
model/game.go
oapi/types.go
usecases/service/ws/client.go
usecases/service/ws/handler.go

- :bug: float to int
- :recycle: 全体送信処理を細分化
- :sparkles: DRAW_START

DRAW_START

---

interfaces/repository/room_impl.go
model/game.go
usecases/service/ws/handler.go
util/random/shuffle.go

- :fire: Remove impl-todo
- :sparkles: Fill struct fields
- :boom: Index to AreaId
- :recycle: Fill model.Room
- :fire: Remove SetupDrawerSeq
- :fire: Remove todo comment

Remove solved TODO

---

infrastructure/router.go
main.go

クライアントの開発環境に需要があるっぽい
- :sparkles: Add custom base endpoint
- :recycle: Add skipper

エンドポイントをフラグで/api変えられる設定をつける

---

interfaces/handler/room.go
model/user.go
usecases/service/ws/client.go
usecases/service/ws/handler.go
usecases/service/ws/ws.go
util/canvas/canvas.go

いつかやらんとな～と思っていたので今
- :recycle: Wrap error
- :recycle: Update error msg
- :recycle: websocketのエラーでechoハンドラーが止まると不整合が起こるのでログだけにする

エラーハンドリングちゃんと

---

usecases/service/ws/handler.go

✨impl sendshowevent

---

model/game.go
usecases/service/ws/handler.go

✨ impl SHOW

---

model/game.go
model/room.go
usecases/service/ws/handler.go

🐛 AllDrawPhaseの修正

---

docs/openapi.yml
interfaces/repository/room_impl.go
oapi/types.go
usecases/service/ws/handler.go

Closes #51
Closes #52
- :sparkles: Feat ROOM_SET_OPTION
- :sparkles: Feat ROOM_UPDATE_OPTION

ROOM_SET_OPTION,ROOM_UPDATE_OPTION

---

interfaces/repository/room_impl.go
model/game.go
usecases/repository/room.go
usecases/service/ws/client.go
usecases/service/ws/handler.go

- :sparkles: BREAK_ROOM
- :sparkles: Add case model.GameShowPhaseEnd

BREAK_ROOM

---

util/random/shuffle.go

👍 場所割アルゴリズムの変更

---

usecases/service/ws/handler.go

🐛 fix error

---

usecases/service/ws/errors.go
usecases/service/ws/handler.go

🐛 人数のバリデーションの追加

---

usecases/service/ws/handler.go

- :boom: show_nextをbloadcastにする
- :boom: phaseの変更をホストだけにする
- :bug: showcountをanswerで++

fix sendXXX

---

usecases/service/ws/handler.go

- :recycle: sendDrawStartEventの中で複数回sendを飛ばすようにする
- :recycle: receiveDrawSendEventでbloadcastするのをやめる
- :recycle: answersendでbloadcast使うのやめる

複数クライアント送信はsend~~のみで行う

---

usecases/service/ws/handler.go

:bug: Fix nil pointer

---

usecases/service/ws/util.go

🐛 結果発表が最後まで行われないバグの修正

---

docs/openapi.yml

ref https://github.com/21hack02win/nascalay-frontend/pull/123

⚙ showcase でホストするように

---

interfaces/handler/ping.go
interfaces/handler/room.go

:recycle: use c.JSON when successed

---

.golangci.yml
usecases/service/ws/client.go
usecases/service/ws/handler.go
usecases/service/ws/server.go
usecases/service/ws/util.go
usecases/service/ws/ws.go

サーバーからクライアントに送るイベントなのに`(*Client).sendEvent`となっていたのが分かりにくかったのでリファクタ
適切なファイル分割とか、チェーン長すぎる問題、ローカルロガー問題は別PRで

add ws.RoomServer
